version: '3'

services:
  web:
    image: myapp:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    ports:
      - "5000:5000"
    networks:
      - app_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_net

networks:
  app_net:
