clients:
  - url: "http://loki:3100/loki/api/v1/push"

positions:
  filename: /tmp/positions.yaml

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs

- job_name: nginx
  pipeline_stages:
  - docker: {}
  static_configs:
  - targets:
      - nginx
    labels:
      job: nginx_access_logs
      __path__: /var/log/nginx/access.log
  - targets:
      - nginx
    labels:
      job: nginx_error_logs
      __path__: /var/log/nginx/error.log
