global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker'
    static_configs:
      - targets: ['docker.for.mac.localhost:9323']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

remote_write:
  - url: "http://loki:3100/api/prom/push"

