version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    ports: 
      - "443:443"
    networks:
      - mynetwork

  helloapp1:
    image: helloapp1
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
    networks:
      - mynetwork

  helloapp2:
    image: helloapp2
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
    networks:
      - mynetwork

networks:
  mynetwork:
