version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - mynetwork
  helloapp:
    image: helloapp
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
    networks:
      - mynetwork
  worldapp:
    image: worldapp
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
    networks:
      - mynetwork
networks:
  mynetwork:
